<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Download</name>
   <tag></tag>
   <elementGuidId>99bb2c5a-7dc1-482b-a6fd-eec8a104adf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/p/a[@class='download-link']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
